[build]
publish = "public"
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[build.environment]
HUGO_VERSION = "0.83.1"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
